<Project>

  <PropertyGroup>

    <uTestVersion>0.0.1</uTestVersion>

    <Version>$(uTestVersion)</Version>
    <PackageVersion>$(uTestVersion)</PackageVersion>

    <FileVersion>$(uTestVersion).0</FileVersion>
    <AssemblyVersion>$(uTestVersion).0</AssemblyVersion>

    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/DanielWillett/Unturned.uTest</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>

    <PackageTags>Unturned;SDG;unit;integration;testing;tests;modding;plugins;RocketMod;Rocket-Mod;OpenMod;Open-Mod;LDM;Legally-Distinct-Missile;LegallyDistinctMissile;Uncreated</PackageTags>

    <Authors>Daniel Willett</Authors>
    <Company>$(Authors)</Company>

    <PackageReadmeFile>README.md</PackageReadmeFile>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <NeutralLanguage>en-US</NeutralLanguage>
    <DebugType>portable</DebugType>

  </PropertyGroup>

  <PropertyGroup>

    <UnturnedMSBuildVersion>1.0.1</UnturnedMSBuildVersion>

  </PropertyGroup>

</Project>