//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uTest.Adapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uTest.Adapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering tests from the following sources:.
        /// </summary>
        internal static string LogDiscoveringTests {
            get {
                return ResourceManager.GetString("LogDiscoveringTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown while reading symbols for {0}..
        /// </summary>
        internal static string LogExceptionReadingSymbols {
            get {
                return ResourceManager.GetString("LogExceptionReadingSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown while searching module {0}..
        /// </summary>
        internal static string LogExceptionSearchingModule {
            get {
                return ResourceManager.GetString("LogExceptionSearchingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach debugger to Unturned process (PID {0})..
        /// </summary>
        internal static string LogFailedToDebug {
            get {
                return ResourceManager.GetString("LogFailedToDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping assembly &quot;{0}&quot; because it doesn&apos;t reference {1}..
        /// </summary>
        internal static string LogSkippingSourceDoesntReferenceUTest {
            get {
                return ResourceManager.GetString("LogSkippingSourceDoesntReferenceUTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping assembly &quot;{0}&quot; because it could not be read as a valid module..
        /// </summary>
        internal static string LogSkippingSourceFailedToReadFile {
            get {
                return ResourceManager.GetString("LogSkippingSourceFailedToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping assembly &quot;{0}&quot; because the file no longer exists or the runner lacks the required permissions..
        /// </summary>
        internal static string LogSkippingSourceFileNotFound {
            get {
                return ResourceManager.GetString("LogSkippingSourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered {0} test(s) in {1:F1} ms..
        /// </summary>
        internal static string LogTestDiscoveryFinished {
            get {
                return ResourceManager.GetString("LogTestDiscoveryFinished", resourceCulture);
            }
        }
    }
}
