using uTest.Module;
using Random = System.Random;

namespace uTest;

/// <summary>
/// Used to create unique Steam64 IDs within the 'Dev' universe.
/// </summary>
internal sealed class SteamIdPool
{
    private readonly SteamIdGenerationStyle _style;

    private long _nextAccountNumber;

    // note:
    // seems like theres a bunch of steam accounts from
    // march 2020 allocated near the very high numbers,
    // so we just use this range instead

    private const int MinAccountId = 0b01111111000000000000110111110000;
    private const int MaxAccountId = 0b01111111000000111111110111000000;
    private const uint InstanceIdNormal = 1u;
    private const uint InstanceIdInstance = 9034;

    // having the last digits all the same makes it easier to tell its a bot
    // obv real accounts can also end in 0418 but not likely to happen much.
    // 418 is from the april fools HTTP status code, also C418
    internal const int FinalDigitsFactor = 10000;
    internal const uint FinalDigits = 0418;

    private const ulong MaxIdDev = (ulong)EUniverse.k_EUniverseDev << 56
                                   | ((ulong)EAccountType.k_EAccountTypeIndividual & 0b1111) << 52
                                   | ((ulong)InstanceIdNormal & 0b11111111111111111111) << 32
                                   | uint.MaxValue;

    private const ulong MaxIdRandom = (ulong)EUniverse.k_EUniversePublic << 56
                                   | ((ulong)EAccountType.k_EAccountTypeIndividual & 0b1111) << 52
                                   | ((ulong)InstanceIdNormal & 0b11111111111111111111) << 32
                                   | uint.MaxValue;

    /// <summary>
    /// Determines whether or not <paramref name="id"/> is generated by any configuration of <see cref="SteamIdPool"/>.
    /// Can theoretically produce false positives.
    /// </summary>
    internal bool IsLikelyGeneratedId(CSteamID id)
    {
        if (id.m_SteamID % FinalDigitsFactor != FinalDigits)
        {
            return false;
        }

        if (id.GetUnAccountInstance() == InstanceIdInstance)
            return true;

        if (id.GetAccountID().m_AccountID is < MinAccountId or > MaxAccountId + 1024)
            return id.GetEUniverse() == EUniverse.k_EUniverseDev || id.GetUnAccountInstance() == 0b10u;

        return id.GetUnAccountInstance() == 1 && id.GetEUniverse() == EUniverse.k_EUniversePublic;
    }

    // There are between 216,425 and 216,399 available steam IDs.
    // Probably won't run out
    internal SteamIdPool(SteamIdGenerationStyle style)
    {
        _style = style;
        ResetPoolCounter();
    }

    private void ResetPoolCounter()
    {
        EUniverse univ = _style == SteamIdGenerationStyle.DevUniverse
            ? EUniverse.k_EUniverseDev
            : EUniverse.k_EUniversePublic;

        ulong id = (ulong)univ << 56 | (((ulong)EAccountType.k_EAccountTypeIndividual & 0b1111) << 52 | ((ulong)InstanceIdNormal & 0b11111111111111111111) << 32);
        _nextAccountNumber = (long)(id / FinalDigitsFactor) + new Random().Next(MinAccountId / FinalDigitsFactor, MaxAccountId / FinalDigitsFactor);
    }

    internal CSteamID GetUniqueCSteamID()
    {
        int c = 0;
        while (c < 2)
        {
            ulong acctNum = unchecked( (ulong)Interlocked.Increment(ref _nextAccountNumber) );
            acctNum = acctNum * FinalDigitsFactor + FinalDigits;
            if (acctNum <= _style switch
            {
                SteamIdGenerationStyle.DevUniverse => MaxIdDev,
                _ => MaxIdRandom
            })
            {
                return new CSteamID(acctNum);
            }

            ResetPoolCounter();
            ++c;
        }

        return new CSteamID(
            (_style switch
            {
                SteamIdGenerationStyle.DevUniverse => MaxIdDev,
                _ => MaxIdRandom
            } & 0xFFFFFFFF00000000) / FinalDigitsFactor * FinalDigitsFactor + FinalDigits
        );
    }
}