//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify &quot;{0}&quot;, this actor has been destroyed..
        /// </summary>
        internal static string ActorDestroyedExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ActorDestroyedExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify &quot;{0}&quot;, the current client does not have authority over it. This is usually because this library is running on a client playing on a server..
        /// </summary>
        internal static string ActorMissingAuthorityExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ActorMissingAuthorityExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify &quot;{0}&quot;, it&apos;s currently being driven..
        /// </summary>
        internal static string ActorMissingAuthorityExceptionVehicleDriven {
            get {
                return ResourceManager.GetString("ActorMissingAuthorityExceptionVehicleDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify &quot;{0}&quot;, this actor is out of bounds of the world..
        /// </summary>
        internal static string ActorOutOfBoundsExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ActorOutOfBoundsExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assertion expression for a DateTimeOffset can not both define a tolerance and check that offsets are the same..
        /// </summary>
        internal static string AssertionExpressionCombinedDateTimeOffsetComparisonWithTolerance {
            get {
                return ResourceManager.GetString("AssertionExpressionCombinedDateTimeOffsetComparisonWithTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination of assertion expressions is not supported..
        /// </summary>
        internal static string AssertionExpressionInvalidCombination {
            get {
                return ResourceManager.GetString("AssertionExpressionInvalidCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion expression &quot;{0}&quot; missing terminal point. This can happen when a modifier expression is used without supplying a constant value, such as &apos;Is.Not&apos; (in NUnit style)..
        /// </summary>
        internal static string AssertionExpressionMissingParent {
            get {
                return ResourceManager.GetString("AssertionExpressionMissingParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature can only be used on the game thread..
        /// </summary>
        internal static string GameThreadExceptionDefault {
            get {
                return ResourceManager.GetString("GameThreadExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type used for THitInfo type parameter..
        /// </summary>
        internal static string HitInfoUnknownType {
            get {
                return ResourceManager.GetString("HitInfoUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected object and interactable rubble to belong to the same object..
        /// </summary>
        internal static string LevelObjectInconsistantRubble {
            get {
                return ResourceManager.GetString("LevelObjectInconsistantRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an instance of test class &quot;{0}&quot;..
        /// </summary>
        internal static string LogErrorCreatingRunner {
            get {
                return ResourceManager.GetString("LogErrorCreatingRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type(s) {0} do not meet the generic constraints for test {1}..
        /// </summary>
        internal static string LogErrorGenericConstraints {
            get {
                return ResourceManager.GetString("LogErrorGenericConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestArgsAttribute was given {0} parameter(s) but test {1} should have exactly {2}..
        /// </summary>
        internal static string LogErrorMismatchedArgsParameterCount {
            get {
                return ResourceManager.GetString("LogErrorMismatchedArgsParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeArgsAttribute was given {0} type parameter(s) but class or method {1} should have exactly {2}..
        /// </summary>
        internal static string LogErrorMismatchedArgsTypeParameterCount {
            get {
                return ResourceManager.GetString("LogErrorMismatchedArgsTypeParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} can not be converted to type {1} for parameter &quot;{2}&quot; in test {3}..
        /// </summary>
        internal static string LogErrorMismatchedParameterType {
            get {
                return ResourceManager.GetString("LogErrorMismatchedParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compile test &apos;{0}&apos;, it&apos;s type ({1}) is missing a public parameterless constructor..
        /// </summary>
        internal static string LogErrorMissingConstructor {
            get {
                return ResourceManager.GetString("LogErrorMissingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member referred to by &apos;From&apos; property ({0}) does not exist in {1}..
        /// </summary>
        internal static string LogErrorMissingFromMember {
            get {
                return ResourceManager.GetString("LogErrorMissingFromMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all parameters on test {0} in {1} have value sets or ranges. This could also be caused by a range containing too many elements, as a test can not have more than {2} variations..
        /// </summary>
        internal static string LogErrorParametersMissingValues {
            get {
                return ResourceManager.GetString("LogErrorParametersMissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching {0} failed: &apos;{1}&apos;..
        /// </summary>
        internal static string LogErrorPatchFailed {
            get {
                return ResourceManager.GetString("LogErrorPatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered accessing member referred to by &apos;From&apos; property ({0}) in {1}..
        /// </summary>
        internal static string LogErrorReadingFromMember {
            get {
                return ResourceManager.GetString("LogErrorReadingFromMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test UID &quot;{0}&quot; could not be linked to a test variation, it will be skipped..
        /// </summary>
        internal static string LogErrorUnresolvedTestUid {
            get {
                return ResourceManager.GetString("LogErrorUnresolvedTestUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} test UID(s) were not able to be linked to test variations..
        /// </summary>
        internal static string LogErrorUnresolvedTestUids {
            get {
                return ResourceManager.GetString("LogErrorUnresolvedTestUids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading asset {0}..
        /// </summary>
        internal static string LogTraceLoadingAsset {
            get {
                return ResourceManager.GetString("LogTraceLoadingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping asset {0}..
        /// </summary>
        internal static string LogTraceSkippingAsset {
            get {
                return ResourceManager.GetString("LogTraceSkippingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations are not supported on the NullActor..
        /// </summary>
        internal static string NotSupportedExceptionNullActor {
            get {
                return ResourceManager.GetString("NotSupportedExceptionNullActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level objects do not support health..
        /// </summary>
        internal static string NotSupportedExceptionObjectHealth {
            get {
                return ResourceManager.GetString("NotSupportedExceptionObjectHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object was never spawned because it was missing an asset or prefab..
        /// </summary>
        internal static string NotSupportedExceptionObjectNotSpawned {
            get {
                return ResourceManager.GetString("NotSupportedExceptionObjectNotSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads do not support health..
        /// </summary>
        internal static string NotSupportedExceptionRoadHealth {
            get {
                return ResourceManager.GetString("NotSupportedExceptionRoadHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals do not support changing scale..
        /// </summary>
        internal static string NotSupportedExceptionSetScaleAnimal {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetScaleAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barricades do not support changing scale..
        /// </summary>
        internal static string NotSupportedExceptionSetScaleBarricade {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetScaleBarricade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players do not support changing scale..
        /// </summary>
        internal static string NotSupportedExceptionSetScalePlayer {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetScalePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures do not support changing scale..
        /// </summary>
        internal static string NotSupportedExceptionSetScaleStructure {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetScaleStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles do not support changing scale..
        /// </summary>
        internal static string NotSupportedExceptionSetScaleVehicle {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetScaleVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombies do not support changing scale..
        /// </summary>
        internal static string NotSupportedExceptionSetScaleZombie {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetScaleZombie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects do not support changing position, rotation, or scale..
        /// </summary>
        internal static string NotSupportedExceptionSetTransformObject {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetTransformObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads do not support changing position, rotation, or scale..
        /// </summary>
        internal static string NotSupportedExceptionSetTransformRoad {
            get {
                return ResourceManager.GetString("NotSupportedExceptionSetTransformRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources do not support changing position, rotation, or scale..
        /// </summary>
        internal static string NotSupportedExceptionTransformResource {
            get {
                return ResourceManager.GetString("NotSupportedExceptionTransformResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected placeable drop and serverside data to have the same instance ID..
        /// </summary>
        internal static string PlaceablesInconsistantInstanceIDs {
            get {
                return ResourceManager.GetString("PlaceablesInconsistantInstanceIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflection failure encountered, meaning SDG changed something that broke this library. Open an issue to get this fixed. Member: &quot;{0}&quot;..
        /// </summary>
        internal static string ReflectionFailureWithMember {
            get {
                return ResourceManager.GetString("ReflectionFailureWithMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test system has already started shutting down and can&apos;t invoke any more RunAndWaits..
        /// </summary>
        internal static string RunAndWaitShuttingDown {
            get {
                return ResourceManager.GetString("RunAndWaitShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting on main thread dispatch..
        /// </summary>
        internal static string RunAndWaitTimeoutFailure {
            get {
                return ResourceManager.GetString("RunAndWaitTimeoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while running a callback on the main thread from &quot;{0}&quot;..
        /// </summary>
        internal static string RunOnMainThreadError {
            get {
                return ResourceManager.GetString("RunOnMainThreadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string TestResultCancelled {
            get {
                return ResourceManager.GetString("TestResultCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result: {0}..
        /// </summary>
        internal static string TestResultExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("TestResultExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string TestResultFail {
            get {
                return ResourceManager.GetString("TestResultFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconclusive.
        /// </summary>
        internal static string TestResultInconclusive {
            get {
                return ResourceManager.GetString("TestResultInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string TestResultInProgress {
            get {
                return ResourceManager.GetString("TestResultInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string TestResultPass {
            get {
                return ResourceManager.GetString("TestResultPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string TestResultSkipped {
            get {
                return ResourceManager.GetString("TestResultSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Out.
        /// </summary>
        internal static string TestResultTimeout {
            get {
                return ResourceManager.GetString("TestResultTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unturned instance failed to start with uTest..
        /// </summary>
        internal static string UnturnedStartExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("UnturnedStartExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unturned.uTest (Runner).
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
