using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Reflection;
using System.Text;
using uTest;
using Assert = NUnit.Framework.Assert;

#pragma warning disable IDE0051
#pragma warning disable CS8500

// ReSharper disable UnusedParameter.Local
// ReSharper disable UnusedTypeParameter
// ReSharper disable InconsistentNaming
// ReSharper disable LocalizableElement

namespace uTest_Test;

public class ManagedMethodIdentifierTests
{
    private interface IToken
    {
        bool IsMatch(in ManagedIdentifierTokenizer tokenizer);
    }

    private class ContentToken(ManagedIdentifierTokenType type, string content) : IToken
    {
        public bool IsMatch(in ManagedIdentifierTokenizer tokenizer)
        {
            return tokenizer.TokenType == type
                   && tokenizer.Value.Equals(content, StringComparison.Ordinal);
        }

        public override string ToString() => $"Token = {type}, Value = {content}";
    }

    private class ArityToken(ManagedIdentifierTokenType type, int arity) : IToken
    {
        public bool IsMatch(in ManagedIdentifierTokenizer tokenizer)
        {
            return tokenizer.TokenType == type
                   && tokenizer.Arity == arity;
        }

        public override string ToString() => $"Token = {type}, Arity = {arity}";
    }

    private class ArrayToken(bool isSz, int rank) : IToken
    {
        public bool IsMatch(in ManagedIdentifierTokenizer tokenizer)
        {
            return tokenizer.TokenType == ManagedIdentifierTokenType.Array
                   && tokenizer.IsSzArray == isSz
                   && tokenizer.ArrayRank == rank;
        }

        public override string ToString() => $"Token = Array, IsSzArray = {isSz}, Rank = {rank}";
    }
    private class GenericReferenceToken(bool isMethod, int index) : IToken
    {
        public bool IsMatch(in ManagedIdentifierTokenizer tokenizer)
        {
            return tokenizer.TokenType == ManagedIdentifierTokenType.TypeGenericParameterReference + (isMethod ? 1 : 0)
                   && tokenizer.GenericReferenceIndex == index;
        }

        public override string ToString() => $"Token = {ManagedIdentifierTokenType.TypeGenericParameterReference + (isMethod ? 1 : 0)}, TypeParameterIndex = {index}";
    }

    private static void AssertTypeStructureEquals(string managedType, IToken[] tokens, string? expected = null)
    {
        AssertStructureEquals(managedType, tokens, ManagedIdentifierKind.Type, expected);
    }
    private static void AssertMethodStructureEquals(string managedType, IToken[] tokens, string? expected = null)
    {
        AssertStructureEquals(managedType, tokens, ManagedIdentifierKind.Method, expected);
    }
    private static void AssertStructureEquals(string managedType, IToken[] tokens, ManagedIdentifierKind idKind, string? expected)
    {
        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer(managedType, idKind);
        CheckTokens(ref tokenizer, tokens);
        tokenizer.Reset();
        CheckTokens(ref tokenizer, tokens);

        if (expected == null)
        {
            if (managedType.EndsWith("()"))
                expected = managedType.Substring(0, managedType.Length - 2);
            else
                expected = managedType;
        }
        
        Assert.That(ManagedIdentifier.Normalize(managedType, idKind), Is.EqualTo(expected));
        return;

        static void CheckTokens(ref ManagedIdentifierTokenizer tokenizer, IToken[] tokens)
        {
            int index = 0;
            while (tokenizer.MoveNext())
            {
                if (index >= tokens.Length)
                    Assert.Fail($"Token overflow: {tokenizer.TokenType}.");

                IToken token = tokens[index];
                if (!token.IsMatch(in tokenizer))
                {
                    Assert.Fail($"Token mismatch: [ {tokenizer.TokenType}, {tokenizer.Value.ToString()} ], expected: [ {token} ].");
                }

                ++index;
            }

            if (index != tokens.Length)
                Assert.Fail($"Token not reached: {tokens[index]}.");
        }
    }

    // NOTE: some test cases generated by ChatGPT
    [NUnit.Framework.Test]
    public void ManagedTypes()
    {
        AssertTypeStructureEquals(
            @"System.String",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String")
            ]
        );
        
        AssertTypeStructureEquals(
            @"Namespace.Class`1",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.Outer+Inner",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Outer"),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"Inner")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.GenericOuter`2+GenericInner`3",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"GenericOuter"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"GenericInner"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 3)
            ]
        );

        AssertTypeStructureEquals(
            @"A`1+B`1",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"A"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"B"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1)
            ]
        );

        AssertTypeStructureEquals(
            @"A`1+B`1+C`1",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"A"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"B"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"C"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1)
            ]
        );

        AssertTypeStructureEquals(
            @"A`16+B`207",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"A"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 16),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"B"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 207)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class With Space'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class With Space")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'𝐂𝐥𝐚𝐬𝐬🦄'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"𝐂𝐥𝐚𝐬𝐬🦄")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class.Name.With.Dots'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class.Name.With.Dots")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class\\WithBackslash'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class\WithBackslash")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class\'WithQuote'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class'WithQuote")
            ]
        );

        AssertTypeStructureEquals(
            @"Κατηγορία.Δοκιμή",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Κατηγορία"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Δοκιμή")
            ]
        );

        AssertTypeStructureEquals(
            @"سم.اختبار",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"سم"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"اختبار")
            ]
        );

        AssertTypeStructureEquals(
            @"命名空間.类名",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"命名空間"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"类名")
            ]
        );

        AssertTypeStructureEquals(
            @"DeepNamespace.Level1.Level2.Level3.Level4.Level5.DeepClass`1+Nested`2+DeepNested`3",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"DeepNamespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Level1"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Level2"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Level3"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Level4"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Level5"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"DeepClass"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"Nested"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"DeepNested"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 3)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.DeepGenericOuter`4+Middle`3+Inner`2",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"DeepGenericOuter"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 4),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"Middle"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 3),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"Inner"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class With 🚀 Unicode 😈 and Spaces'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class With 🚀 Unicode 😈 and Spaces")
            ]
        );

        AssertTypeStructureEquals(
            "Namespace.'__Hidden\u2028LineBreak'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, "__Hidden\u2028LineBreak")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'EndsWithBackslash\\'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"EndsWithBackslash\")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'\\StartsWithBackslash'",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"\StartsWithBackslash")
            ]
        );
    }

    [NUnit.Framework.Test]
    public void ManagedMethods()
    {
        AssertMethodStructureEquals(
            @"Method",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32,System.String)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32[],System.String[,],System.Object[,,])",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ArrayToken(true, 1),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 2),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Object"),
                new ArrayToken(false, 3),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32*)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.Pointer, @"*"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`1(System.Collections.Generic.List`1<System.String>)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ArityToken(ManagedIdentifierTokenType.Arity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`2(!0,!!0)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ArityToken(ManagedIdentifierTokenType.Arity, 2),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new GenericReferenceToken(true, 0),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method With Space'()",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method With Space"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'𝒲𝒾𝓉𝒽 Unicode ♥'()",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"𝒲𝒾𝓉𝒽 Unicode ♥"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method.With.Dots'(System.Int32)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method.With.Dots"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method\\WithBackslash'()",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method\WithBackslash"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method\'WithQuote'()",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method'WithQuote"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @".ctor(System.Int32)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @".ctor"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Finalize()",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Finalize"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"op_Addition(System.Int32,System.Int32)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"op_Addition"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"System.Collections.Generic.IEnumerable<System.String>.GetEnumerator()",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"IEnumerable<System.String>"),
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"GetEnumerator"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<!0>>)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`1(System.Collections.Generic.List`1<System.Collections.Generic.Dictionary`2<!0,!!0>>)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ArityToken(ManagedIdentifierTokenType.Arity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new GenericReferenceToken(true, 0),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            """
            Method(System.Collections.Generic.Dictionary`2<
                       System.String,
                       System.Collections.Generic.Dictionary`2<
                           System.Int32,
                           System.Collections.Generic.Dictionary`2<
                               System.Object,
                               System.Collections.Generic.List`1<
                                   System.Collections.Generic.Dictionary`2<
                                       System.String,System.Int32
                                   >
                               >
                           >
                       >
                   >)
            """,
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Object"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 2),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.Dictionary`2<System.Int32,System.Collections.Generic.Dictionary`2<System.Object,System.Collections.Generic.List`1<System.Collections.Generic.Dictionary`2<System.String,System.Int32>>>>>)"
        );
        
        AssertMethodStructureEquals(
            @"Method(System.String[,,,,])",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 5),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32[,,][,])",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ArrayToken(false, 3),
                new ArrayToken(false, 2),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`3(!0,!!0,System.Collections.Generic.List`1<!!2>)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ArityToken(ManagedIdentifierTokenType.Arity, 3),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new GenericReferenceToken(true, 0),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenTypeParameters, @"<"),
                new GenericReferenceToken(true, 2),
                new ContentToken(ManagedIdentifierTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );

        AssertMethodStructureEquals(
            @"'Weird\'Name\\With\'Escapes'(System.Int32*,System.String[,,],!0)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Weird'Name\With'Escapes"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.Pointer, @"*"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 3),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );

        AssertMethodStructureEquals(
            @"System.Collections.Generic.IDisposable.Dispose()",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"Collections"),
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"Generic"),
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"IDisposable"),
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Dispose"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );

        AssertMethodStructureEquals(
            @"System.Action<System.String>.Invoke(System.String)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.MethodImplementationTypeSegment, @"Action<System.String>"),
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Invoke"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ]
        );
    }

    [NUnit.Framework.Test]
    public void ManagedTypesWhitespace()
    {
        //AssertTypeStructureEquals(
        //    @"Namespace . Class",
        //    [
        //        new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
        //        new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class")
        //    ],
        //    expected: "Namespace.Class"
        //);

        AssertTypeStructureEquals(
            @"Namespace. Outer + Inner",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Outer"),
                new ContentToken(ManagedIdentifierTokenType.NestedTypeSegment, @"Inner")
            ],
            expected: "Namespace.Outer+Inner"
        );

        AssertTypeStructureEquals(
            @"Namespace . 'Class With Space '",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class With Space ")
            ],
            expected: "Namespace.'Class With Space '"
        );

        AssertTypeStructureEquals(
            @"Namespace.   Class ` 1",
            [
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Class"),
                new ArityToken(ManagedIdentifierTokenType.TypeArity, 1)
            ],
            expected: "Namespace.Class`1"
        );

    }

    [NUnit.Framework.Test]
    public void ManagedMethodsWhitespace()
    {
        AssertMethodStructureEquals(
            @"Method `1(System.Int32)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ArityToken(ManagedIdentifierTokenType.Arity, 1),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ],
            expected: "Method`1(System.Int32)"
        );

        AssertMethodStructureEquals(
            @"Method(System. Int32 ,  System. String)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.Int32,System.String)"
        );

        AssertMethodStructureEquals(
            @"Method(System.String [ , , ])",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 3),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.String[,,])"
        );

        AssertMethodStructureEquals(
            @"Method(System.Int32 *)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.Pointer, @"*"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.Int32*)"
        );

        AssertMethodStructureEquals(
            @"'Method With Space' ( System.String ,System.Int32 )",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method With Space"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ],
            expected: "'Method With Space'(System.String,System.Int32)"
        );

        AssertMethodStructureEquals(
            @"Method(System.String ,   System.Int32 ,   System.Object)",
            [
                new ContentToken(ManagedIdentifierTokenType.MethodName, @"Method"),
                new ContentToken(ManagedIdentifierTokenType.OpenParameters, @"("),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedIdentifierTokenType.NextParameter, @","),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedIdentifierTokenType.TypeSegment, @"Object"),
                new ContentToken(ManagedIdentifierTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.String,System.Int32,System.Object)"
        );
    }

    [NUnit.Framework.Test]
    [TestCase(@"Method(NamespaceA.NamespaceB.Class)")]
    [TestCase(@"'𝐌𝐲 𝗮𝘄𝗲𝘀𝗼𝗺𝗲 method w\\𝘢𝘯 𝒊𝒏𝒂𝒄𝒄𝒆𝒔𝒔𝒊𝒃𝒍𝒆 𝙣𝙖𝙢𝙚 🤦‍♂️'(NamespaceA.NamespaceB.Class)")]
    [TestCase(@"Method(System.String,System.Int32)")]
    [TestCase(@"Method(System.String[])")]
    [TestCase(@"Method`1(!0[], !!0[])")]
    [TestCase(@"Method`1(!0*, !!0*)")]
    [TestCase(@"Method`1(!0&, !!0&)")]
    [TestCase(@"Method(System.String*[,]&)")]
    [TestCase(@"Method(System.Int32*[*]&)")]
    [TestCase(@"Method(System.Collections.Generic.List`1<System.String>)")]
    [TestCase(@"'Method Name'(System.Collections.Generic.List`1<System.String>)")]
    [TestCase(@"Method(!0)")]
    [TestCase(@"Method`1(!!0)")]
    [TestCase(@"Method`1")]
    [TestCase(@"Method")]
    [TestCase(@"Method ")]
    [TestCase(@" Method ")]
    [TestCase(@" Method")]
    [TestCase(@"'Method Name'")]
    [TestCase(@"'Method \'Name'")]
    [TestCase(@"'1Method'()")]
    [TestCase(@"Method(System.Collections.Generic.List`1<!0>)")]
    [TestCase(@"System.Collections.Generic.IEnumerable<T>.GetEnumerator")]
    [TestCase(@".ctor")]
    [TestCase(@".cctor")]
    [TestCase(@"'.ctor'")]
    [TestCase(@"'.cctor'")]
    [TestCase(@"MethodName`2(ParamTypeA,ParamTypeB)")]
    [TestCase(@"MethodName`2()")]
    [TestCase(@"Method(System.Collections.Generic.List`1+Enumerator<System.String>)")]
    [TestCase(@"''")]
    [TestCase(@"M")]
    [TestCase(@"Method(System.String[,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,])")]
    [TestCase(@"'M'")]
    public void PrintTokenizers(string name)
    {
        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer(name, ManagedIdentifierKind.Method);

        StringBuilder sb = new StringBuilder();
        TextWriter sw = new StringWriter();
        using ManagedIdentifierBuilder b1 = new ManagedIdentifierBuilder(sb);
        using ManagedIdentifierBuilder b2 = new ManagedIdentifierBuilder(sw, false);
        
        while (tokenizer.MoveNext())
        {
            Console.WriteLine($"{tokenizer.TokenType,-32} \"{tokenizer.Value.ToString()}\"");
            if (tokenizer.TokenType == ManagedIdentifierTokenType.Array)
                Console.WriteLine($"  sz: {tokenizer.IsSzArray}, rank: {tokenizer.ArrayRank}.");

            b1.WriteToken(in tokenizer);
            b2.WriteToken(in tokenizer);
        }

        b1.Close();
        b2.Close();

        Console.WriteLine($"B1: \"{b1.ToString()}\"");
        Console.WriteLine($"B2: \"{b2.ToString()}\"");

        Console.WriteLine();
        Console.WriteLine($"Normalized: \"{ManagedIdentifier.Normalize(name, ManagedIdentifierKind.Method)}\".");
    }

    [NUnit.Framework.Test]
    [TestCase(@"(System.String)")]
    [TestCase(@"Method(System.String&[])")]
    [TestCase(@"Method(System.String[**])")]
    [TestCase(@"Method(System.String[,*])")]
    [TestCase(@"Method(System.String[*,])")]
    [TestCase(@"Method(System.String[,%,])")]
    [TestCase(@"Method(System.String[)")]
    [TestCase(@"Method(System.String[")]
    [TestCase(@"Method(System.String])")]
    [TestCase(@"Method(System.String))")]
    [TestCase(@"Method(System.String<System.Int32)")]
    [TestCase(@"Method(System.String<>)")]
    [TestCase(@"Method((System.String)")]
    [TestCase(@"Method(System.String,)")]
    [TestCase(@"Method(System.String<System.String,>)")]
    [TestCase(@"Method`2<System.String,System.Int32>(System.String)")]
    [TestCase(@"Method(!!0)")]
    [TestCase(@"Method(!!1)")]
    [TestCase(@"Method`2(!!2)")]
    [TestCase(@"Method(")]
    [TestCase(@"Method(System..Int32)")]
    [TestCase(@"Method(,)")]
    [TestCase(@"Namespace.Class`999999999")]
    [TestCase(@"Namespace.'Contains\''Quote''")]
    [TestCase(@"Method(!9999999)")]
    [TestCase(@"Method(System..Collections.Generic.List`1<System.String>)")]
    [TestCase(@"Method(System.String,,System.Int32)")]
    [TestCase(@"Method(System.String[,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,])")]
    [TestCase(@"")]
    public void InvalidFormats(string name)
    {
        try
        {
            ManagedIdentifier.Normalize(name, ManagedIdentifierKind.Method);
            Assert.Fail();
        }
        catch (FormatException ex)
        {
            Console.WriteLine(ex);
            Assert.Pass();
        }
    }

    public class NestedType<T>
    {
        private void Method<X>(List<X> list, Dictionary<X, T> dict) { }
    }

    [NUnit.Framework.Test]
    [TestCase("System.Object", typeof(object))]
    [TestCase("System.Int32", typeof(int))]
    [TestCase("System.Version", typeof(Version))]
    [TestCase("GlobalNamespaceType", typeof(GlobalNamespaceType))]
    [TestCase("System.Collections.Generic.Dictionary`2", typeof(Dictionary<,>))]
    [TestCase("System.Collections.Generic.List`1<System.String>", typeof(List<string>))]
    [TestCase("System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.String>>>", typeof(List<List<List<string>>>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<string, int>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.Collections.Generic.Dictionary`2<System.String,System.Int32>,System.Int32>", typeof(Dictionary<Dictionary<string, int>, int>))]
    [TestCase("System.ValueTuple`3<System.String,System.Int32,System.Version>", typeof(ValueTuple<string, int, Version>))]
    [TestCase("uTest_Test.ManagedMethodIdentifierTests+NestedType`1", typeof(NestedType<>))]
    [TestCase("uTest_Test.ManagedMethodIdentifierTests+NestedType`1<uTest_Test.ManagedMethodIdentifierTests+NestedType`1<System.String>>", typeof(NestedType<NestedType<string>>))]
    [TestCase("System.ValueTuple`2<System.String[],System.Int32[,][,,]>", typeof(ValueTuple<string[], int[,,][,]>))]
    [TestCase("System.Collections.Generic.List`1+Enumerator<System.String>", typeof(List<string>.Enumerator))]
    [TestCase("System.Int32*", typeof(int*))]
    [TestCase("System.Int32&", null)] // special case
    public void IsSameTypeAs(string managedType, Type typeCheck)
    {
        // special case
        typeCheck ??= typeof(int).MakeByRefType();

        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer(managedType, ManagedIdentifierKind.Type);

        Assert.That(tokenizer.IsSameTypeAs(typeCheck), Is.True);
    }

    [NUnit.Framework.Test]
    [TestCase("System.Object", typeof(int))]
    [TestCase("System.Version", typeof(IPAddress))]
    [TestCase("GlobalNamespaceType", typeof(OtherGlobalNamespaceType))]
    [TestCase("System.Collections.Generic.Dictionary`2", typeof(Dictionary<string, int>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<,>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<int, string>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<string, string>))]
    [TestCase("System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.String>>>", typeof(List<List<List<int>>>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.Collections.Generic.Dictionary`2<System.String,System.Int32>,System.Int32>", typeof(Dictionary<Dictionary<string, string>, int>))]
    [TestCase("System.ValueTuple`3<System.String,System.Int32,System.Version>", typeof(ValueTuple<string, int>))]
    [TestCase("System.ValueTuple`3<System.String,System.Int32,System.Version>", typeof(ValueTuple<string, int, string>))]
    [TestCase("uTest_Test.ManagedMethodIdentifierTests+NestedType`1", typeof(NestedType<string>))]
    [TestCase("uTest_Test.ManagedMethodIdentifierTests+NestedType`1<System.String>", typeof(NestedType<>))]
    [TestCase("System.ValueTuple`2<System.String[],System.Int32[,][,,]>", typeof(ValueTuple<string[,], int[][]>))]
    [TestCase("System.Collections.Generic.List`1<System.String>+Enumerator", typeof(List<string>.Enumerator))]
    [TestCase("System.Int32*", typeof(string*))]
    [TestCase("System.Int32&", null)] // special case
    public void IsNotSameTypeAs(string managedType, Type typeCheck)
    {
        // special case
        typeCheck ??= typeof(string).MakeByRefType();

        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer(managedType, ManagedIdentifierKind.Type);

        Assert.That(tokenizer.IsSameTypeAs(typeCheck), Is.False);
    }

    [NUnit.Framework.Test]
    public void IsSameTypeAsWithGenericTypeParameter()
    {
        Type type = typeof(NestedType<>);

        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer("Method(!0)", ManagedIdentifierKind.Method);

        Assert.That(tokenizer.MoveNext(), Is.True); // Method
        Assert.That(tokenizer.MoveNext(), Is.True); // (
        Assert.That(tokenizer.MoveNext(), Is.True); // !0

        Assert.That(tokenizer.IsSameTypeAs(type.GetGenericArguments()[0]));
    }

    // ReSharper disable once UnusedTypeParameter
    private void TestMethod<T>() { }

    [NUnit.Framework.Test]
    public void IsSameTypeAsWithGenericMethodParameter()
    {
        MethodInfo? method = typeof(ManagedMethodIdentifierTests)
            .GetMethod(nameof(TestMethod), BindingFlags.NonPublic | BindingFlags.Instance);

        Assert.That(method, Is.Not.Null);

        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer("Method`1(!!0)", ManagedIdentifierKind.Method);

        Assert.That(tokenizer.MoveNext(), Is.True); // Method
        Assert.That(tokenizer.MoveNext(), Is.True); // `1
        Assert.That(tokenizer.MoveNext(), Is.True); // (
        Assert.That(tokenizer.MoveNext(), Is.True); // !!0

        Assert.That(tokenizer.IsSameTypeAs(method!.GetGenericArguments()[0]));
    }

    [NUnit.Framework.Test]
    public void IsSameTypeAsWithGenericNestedTypeParameters()
    {
        Type type = typeof(NestedType<>);
        MethodInfo? method = type.GetMethod("Method", BindingFlags.NonPublic | BindingFlags.Instance);

        Assert.That(method, Is.Not.Null);

        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer(
            """
            Method`1(
                System.Collections.Generic.List`1<!!0>,
                System.Collections.Generic.Dictionary`2<!!0,!0>
            )
            """, ManagedIdentifierKind.Method);

        Assert.That(tokenizer.MoveNext(), Is.True); // Method
        Assert.That(tokenizer.MoveNext(), Is.True); // `1
        Assert.That(tokenizer.MoveNext(), Is.True); // (

        Type xx0 = method!.GetGenericArguments()[0];
        Type x0 = type.GetGenericArguments()[0];
        Assert.That(tokenizer.IsSameTypeAs(typeof(List<>).MakeGenericType(xx0)));
        Assert.That(tokenizer.IsSameTypeAs(typeof(Dictionary<,>).MakeGenericType(xx0, x0)));
    }

    [NUnit.Framework.Test]
    public void IsSameTypeAsWithNestedGenericType_Open()
    {
        Type type = typeof(A<>.B<>);

        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer("uTest_Test.ManagedMethodIdentifierTests+A`1+B`1", ManagedIdentifierKind.Type);

        Assert.That(tokenizer.IsSameTypeAs(type));
    }

    [NUnit.Framework.Test]
    public void IsSameTypeAsWithNestedGenericType_Constructed()
    {
        Type type = typeof(A<int>.B<string>);

        ManagedIdentifierTokenizer tokenizer = new ManagedIdentifierTokenizer("uTest_Test.ManagedMethodIdentifierTests+A`1+B`1<System.Int32,System.String>", ManagedIdentifierKind.Type);

        Assert.That(tokenizer.IsSameTypeAs(type));
    }

    public class A<T>
    {
        public class B<X>;
    }
}