using NUnit.Framework;
using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using uTest.Runner.Util;

// ReSharper disable LocalizableElement

namespace uTest_Test;

public class ManagedMethodTokenizerTests
{
    private interface IToken
    {
        bool IsMatch(in ManagedMethodTokenizer tokenizer);
    }

    private class ContentToken(ManagedMethodTokenType type, string content) : IToken
    {
        public bool IsMatch(in ManagedMethodTokenizer tokenizer)
        {
            return tokenizer.TokenType == type
                   && tokenizer.Value.Equals(content, StringComparison.Ordinal);
        }

        public override string ToString() => $"Token = {type}, Value = {content}";
    }

    private class ArityToken(ManagedMethodTokenType type, int arity) : IToken
    {
        public bool IsMatch(in ManagedMethodTokenizer tokenizer)
        {
            return tokenizer.TokenType == type
                   && tokenizer.Arity == arity;
        }

        public override string ToString() => $"Token = {type}, Arity = {arity}";
    }

    private class ArrayToken(bool isSz, int rank) : IToken
    {
        public bool IsMatch(in ManagedMethodTokenizer tokenizer)
        {
            return tokenizer.TokenType == ManagedMethodTokenType.Array
                   && tokenizer.IsSzArray == isSz
                   && tokenizer.ArrayRank == rank;
        }

        public override string ToString() => $"Token = Array, IsSzArray = {isSz}, Rank = {rank}";
    }
    private class GenericReferenceToken(bool isMethod, int index) : IToken
    {
        public bool IsMatch(in ManagedMethodTokenizer tokenizer)
        {
            return tokenizer.TokenType == ManagedMethodTokenType.TypeGenericParameterReference + (isMethod ? 1 : 0)
                   && tokenizer.GenericReferenceIndex == index;
        }

        public override string ToString() => $"Token = {ManagedMethodTokenType.TypeGenericParameterReference + (isMethod ? 1 : 0)}, TypeParameterIndex = {index}";
    }

    private static void AssertTypeStructureEquals(string managedType, IToken[] tokens, string? expected = null)
    {
        AssertStructureEquals(managedType, tokens, true, expected);
    }
    private static void AssertMethodStructureEquals(string managedType, IToken[] tokens, string? expected = null)
    {
        AssertStructureEquals(managedType, tokens, false, expected);
    }
    private static void AssertStructureEquals(string managedType, IToken[] tokens, bool isTypeOnly, string? expected)
    {
        ManagedMethodTokenizer tokenizer = new ManagedMethodTokenizer(managedType, isTypeOnly);
        int index = 0;
        while (tokenizer.MoveNext())
        {
            if (index >= tokens.Length)
                Assert.Fail($"Token overflow: {tokenizer.TokenType}.");

            IToken token = tokens[index];
            if (!token.IsMatch(in tokenizer))
            {
                Assert.Fail($"Token mismatch: [ {tokenizer.TokenType}, {tokenizer.Value.ToString()} ], expected: [ {token} ].");
            }

            ++index;
        }

        if (index != tokens.Length)
            Assert.Fail($"Token not reached: {tokens[index]}.");

        if (expected == null)
        {
            if (managedType.EndsWith("()"))
                expected = managedType.Substring(0, managedType.Length - 2);
            else
                expected = managedType;
        }
        Assert.That(ManagedMethodTokenizer.Normalize(managedType, isTypeOnly), Is.EqualTo(expected));
    }

    // NOTE: some test cases generated by ChatGPT
    [Test]
    public void ManagedTypes()
    {
        AssertTypeStructureEquals(
            @"System.String",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String")
            ]
        );
        
        AssertTypeStructureEquals(
            @"Namespace.Class`1",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.Outer+Inner",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Outer"),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"Inner")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.GenericOuter`2+GenericInner`3",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"GenericOuter"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"GenericInner"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 3)
            ]
        );

        AssertTypeStructureEquals(
            @"A`1+B`1",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"A"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"B"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1)
            ]
        );

        AssertTypeStructureEquals(
            @"A`1+B`1+C`1",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"A"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"B"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"C"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1)
            ]
        );

        AssertTypeStructureEquals(
            @"A`16+B`207",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"A"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 16),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"B"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 207)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class With Space'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class With Space")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'𝐂𝐥𝐚𝐬𝐬🦄'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"𝐂𝐥𝐚𝐬𝐬🦄")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class.Name.With.Dots'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class.Name.With.Dots")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class\\WithBackslash'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class\WithBackslash")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class\'WithQuote'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class'WithQuote")
            ]
        );

        AssertTypeStructureEquals(
            @"Κατηγορία.Δοκιμή",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Κατηγορία"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Δοκιμή")
            ]
        );

        AssertTypeStructureEquals(
            @"سم.اختبار",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"سم"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"اختبار")
            ]
        );

        AssertTypeStructureEquals(
            @"命名空間.类名",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"命名空間"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"类名")
            ]
        );

        AssertTypeStructureEquals(
            @"DeepNamespace.Level1.Level2.Level3.Level4.Level5.DeepClass`1+Nested`2+DeepNested`3",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"DeepNamespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Level1"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Level2"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Level3"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Level4"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Level5"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"DeepClass"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"Nested"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"DeepNested"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 3)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.DeepGenericOuter`4+Middle`3+Inner`2",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"DeepGenericOuter"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 4),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"Middle"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 3),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"Inner"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2)
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'Class With 🚀 Unicode 😈 and Spaces'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class With 🚀 Unicode 😈 and Spaces")
            ]
        );

        AssertTypeStructureEquals(
            "Namespace.'__Hidden\u2028LineBreak'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, "__Hidden\u2028LineBreak")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'EndsWithBackslash\\'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"EndsWithBackslash\")
            ]
        );

        AssertTypeStructureEquals(
            @"Namespace.'\\StartsWithBackslash'",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"\StartsWithBackslash")
            ]
        );
    }

    [Test]
    public void ManagedMethods()
    {
        AssertMethodStructureEquals(
            @"Method",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32,System.String)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32[],System.String[,],System.Object[,,])",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ArrayToken(true, 1),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 2),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Object"),
                new ArrayToken(false, 3),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32*)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.Pointer, @"*"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`1(System.Collections.Generic.List`1<System.String>)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ArityToken(ManagedMethodTokenType.Arity, 1),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`2(!0,!!0)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ArityToken(ManagedMethodTokenType.Arity, 2),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new GenericReferenceToken(true, 0),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method With Space'()",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method With Space"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'𝒲𝒾𝓉𝒽 Unicode ♥'()",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"𝒲𝒾𝓉𝒽 Unicode ♥"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method.With.Dots'(System.Int32)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method.With.Dots"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method\\WithBackslash'()",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method\WithBackslash"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"'Method\'WithQuote'()",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method'WithQuote"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @".ctor(System.Int32)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @".ctor"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Finalize()",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Finalize"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"op_Addition(System.Int32,System.Int32)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"op_Addition"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"System.Collections.Generic.IEnumerable<System.String>.GetEnumerator()",
            [
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"IEnumerable<System.String>"),
                new ContentToken(ManagedMethodTokenType.MethodName, @"GetEnumerator"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<!0>>)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`1(System.Collections.Generic.List`1<System.Collections.Generic.Dictionary`2<!0,!!0>>)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ArityToken(ManagedMethodTokenType.Arity, 1),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new GenericReferenceToken(true, 0),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            """
            Method(System.Collections.Generic.Dictionary`2<
                       System.String,
                       System.Collections.Generic.Dictionary`2<
                           System.Int32,
                           System.Collections.Generic.Dictionary`2<
                               System.Object,
                               System.Collections.Generic.List`1<
                                   System.Collections.Generic.Dictionary`2<
                                       System.String,System.Int32
                                   >
                               >
                           >
                       >
                   >)
            """,
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Object"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Dictionary"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 2),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.Dictionary`2<System.Int32,System.Collections.Generic.Dictionary`2<System.Object,System.Collections.Generic.List`1<System.Collections.Generic.Dictionary`2<System.String,System.Int32>>>>>)"
        );
        
        AssertMethodStructureEquals(
            @"Method(System.String[,,,,])",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 5),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method(System.Int32[,,][,])",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ArrayToken(false, 3),
                new ArrayToken(false, 2),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
        
        AssertMethodStructureEquals(
            @"Method`3(!0,!!0,System.Collections.Generic.List`1<!!2>)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ArityToken(ManagedMethodTokenType.Arity, 3),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new GenericReferenceToken(true, 0),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"List"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1),
                new ContentToken(ManagedMethodTokenType.OpenTypeParameters, @"<"),
                new GenericReferenceToken(true, 2),
                new ContentToken(ManagedMethodTokenType.CloseTypeParameters, @">"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );

        AssertMethodStructureEquals(
            @"'Weird\'Name\\With\'Escapes'(System.Int32*,System.String[,,],!0)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Weird'Name\With'Escapes"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.Pointer, @"*"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 3),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new GenericReferenceToken(false, 0),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );

        AssertMethodStructureEquals(
            @"System.Collections.Generic.IDisposable.Dispose()",
            [
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"Collections"),
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"Generic"),
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"IDisposable"),
                new ContentToken(ManagedMethodTokenType.MethodName, @"Dispose"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );

        AssertMethodStructureEquals(
            @"System.Action<System.String>.Invoke(System.String)",
            [
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.MethodImplementationTypeSegment, @"Action<System.String>"),
                new ContentToken(ManagedMethodTokenType.MethodName, @"Invoke"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ]
        );
    }

    [Test]
    public void ManagedTypesWhitespace()
    {
        //AssertTypeStructureEquals(
        //    @"Namespace . Class",
        //    [
        //        new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
        //        new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class")
        //    ],
        //    expected: "Namespace.Class"
        //);

        AssertTypeStructureEquals(
            @"Namespace. Outer + Inner",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Outer"),
                new ContentToken(ManagedMethodTokenType.NestedTypeSegment, @"Inner")
            ],
            expected: "Namespace.Outer+Inner"
        );

        AssertTypeStructureEquals(
            @"Namespace . 'Class With Space '",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class With Space ")
            ],
            expected: "Namespace.'Class With Space '"
        );

        AssertTypeStructureEquals(
            @"Namespace.   Class ` 1",
            [
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Namespace"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Class"),
                new ArityToken(ManagedMethodTokenType.TypeArity, 1)
            ],
            expected: "Namespace.Class`1"
        );

    }

    [Test]
    public void ManagedMethodsWhitespace()
    {
        AssertMethodStructureEquals(
            @"Method `1(System.Int32)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ArityToken(ManagedMethodTokenType.Arity, 1),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ],
            expected: "Method`1(System.Int32)"
        );

        AssertMethodStructureEquals(
            @"Method(System. Int32 ,  System. String)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.Int32,System.String)"
        );

        AssertMethodStructureEquals(
            @"Method(System.String [ , , ])",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ArrayToken(false, 3),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.String[,,])"
        );

        AssertMethodStructureEquals(
            @"Method(System.Int32 *)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.Pointer, @"*"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.Int32*)"
        );

        AssertMethodStructureEquals(
            @"'Method With Space' ( System.String ,System.Int32 )",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method With Space"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ],
            expected: "'Method With Space'(System.String,System.Int32)"
        );

        AssertMethodStructureEquals(
            @"Method(System.String ,   System.Int32 ,   System.Object)",
            [
                new ContentToken(ManagedMethodTokenType.MethodName, @"Method"),
                new ContentToken(ManagedMethodTokenType.OpenParameters, @"("),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"String"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Int32"),
                new ContentToken(ManagedMethodTokenType.NextParameter, @","),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"System"),
                new ContentToken(ManagedMethodTokenType.TypeSegment, @"Object"),
                new ContentToken(ManagedMethodTokenType.CloseParameters, @")")
            ],
            expected: "Method(System.String,System.Int32,System.Object)"
        );
    }

    [Test]
    [TestCase(@"Method(NamespaceA.NamespaceB.Class)")]
    [TestCase(@"'𝐌𝐲 𝗮𝘄𝗲𝘀𝗼𝗺𝗲 method w\\𝘢𝘯 𝒊𝒏𝒂𝒄𝒄𝒆𝒔𝒔𝒊𝒃𝒍𝒆 𝙣𝙖𝙢𝙚 🤦‍♂️'(NamespaceA.NamespaceB.Class)")]
    [TestCase(@"Method(System.String,System.Int32)")]
    [TestCase(@"Method(System.String[])")]
    [TestCase(@"Method`1(!0[], !!0[])")]
    [TestCase(@"Method`1(!0*, !!0*)")]
    [TestCase(@"Method`1(!0&, !!0&)")]
    [TestCase(@"Method(System.String*[,]&)")]
    [TestCase(@"Method(System.Int32*[*]&)")]
    [TestCase(@"Method(System.Collections.Generic.List`1<System.String>)")]
    [TestCase(@"'Method Name'(System.Collections.Generic.List`1<System.String>)")]
    [TestCase(@"Method(!0)")]
    [TestCase(@"Method`1(!!0)")]
    [TestCase(@"Method")]
    [TestCase(@"Method ")]
    [TestCase(@" Method ")]
    [TestCase(@" Method")]
    [TestCase(@"'Method Name'")]
    [TestCase(@"'Method \'Name'")]
    [TestCase(@"'1Method'()")]
    [TestCase(@"Method(System.Collections.Generic.List`1<!0>)")]
    [TestCase(@"System.Collections.Generic.IEnumerable<T>.GetEnumerator")]
    [TestCase(@".ctor")]
    [TestCase(@".cctor")]
    [TestCase(@"'.ctor'")]
    [TestCase(@"'.cctor'")]
    [TestCase(@"MethodName`2(ParamTypeA,ParamTypeB)")]
    [TestCase(@"MethodName`2()")]
    [TestCase(@"''")]
    [TestCase(@"M")]
    [TestCase(@"'M'")]
    public void PrintTokenizers(string name)
    {
        ManagedMethodTokenizer tokenizer = new ManagedMethodTokenizer(name, false);

        while (tokenizer.MoveNext())
        {
            Console.WriteLine($"{tokenizer.TokenType,-32} \"{tokenizer.Value.ToString()}\"");
            if (tokenizer.TokenType == ManagedMethodTokenType.Array)
                Console.WriteLine($"  sz: {tokenizer.IsSzArray}, rank: {tokenizer.ArrayRank}.");
        }

        Console.WriteLine();
        Console.WriteLine($"Normalized: \"{ManagedMethodTokenizer.Normalize(name, false)}\".");
    }

    [Test]
    [TestCase(@"(System.String)")]
    [TestCase(@"Method(System.String&[])")]
    [TestCase(@"Method(System.String[**])")]
    [TestCase(@"Method(System.String[,*])")]
    [TestCase(@"Method(System.String[*,])")]
    [TestCase(@"Method(System.String[,%,])")]
    [TestCase(@"Method(System.String[)")]
    [TestCase(@"Method(System.String[")]
    [TestCase(@"Method(System.String])")]
    [TestCase(@"Method(System.String))")]
    [TestCase(@"Method(System.String<System.Int32)")]
    [TestCase(@"Method(System.String<>)")]
    [TestCase(@"Method((System.String)")]
    [TestCase(@"Method(System.String,)")]
    [TestCase(@"Method(System.String<System.String,>)")]
    [TestCase(@"Method`2<System.String,System.Int32>(System.String)")]
    [TestCase(@"Method(!!0)")]
    [TestCase(@"Method(!!1)")]
    [TestCase(@"Method`2(!!2)")]
    [TestCase(@"Method(")]
    [TestCase(@"Method(System..Int32)")]
    [TestCase(@"Method(,)")]
    [TestCase(@"Namespace.Class`999999999")]
    [TestCase(@"Namespace.'Contains\''Quote''")]
    [TestCase(@"Method(!9999999)")]
    [TestCase(@"Method(System..Collections.Generic.List`1<System.String>)")]
    [TestCase(@"Method(System.String,,System.Int32)")]
    [TestCase(@"")]
    public void InvalidFormats(string name)
    {
        try
        {
            ManagedMethodTokenizer.Normalize(name, false);
            Assert.Fail();
        }
        catch (FormatException ex)
        {
            Console.WriteLine(ex);
            Assert.Pass();
        }
    }

    // ReSharper disable once UnusedTypeParameter
    public class NestedType<T>
    {
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once InconsistentNaming
        private void Method<X>(List<X> list, Dictionary<X, T> dict) { }
    }

    [Test]
    [TestCase("System.Object", typeof(object))]
    [TestCase("System.Int32", typeof(int))]
    [TestCase("System.Version", typeof(Version))]
    [TestCase("GlobalNamespaceType", typeof(GlobalNamespaceType))]
    [TestCase("System.Collections.Generic.Dictionary`2", typeof(Dictionary<,>))]
    [TestCase("System.Collections.Generic.List`1<System.String>", typeof(List<string>))]
    [TestCase("System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.String>>>", typeof(List<List<List<string>>>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<string, int>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.Collections.Generic.Dictionary`2<System.String,System.Int32>,System.Int32>", typeof(Dictionary<Dictionary<string, int>, int>))]
    [TestCase("System.ValueTuple`3<System.String,System.Int32,System.Version>", typeof(ValueTuple<string, int, Version>))]
    [TestCase("uTest_Test.ManagedMethodTokenizerTests+NestedType`1", typeof(NestedType<>))]
    [TestCase("uTest_Test.ManagedMethodTokenizerTests+NestedType`1<uTest_Test.ManagedMethodTokenizerTests+NestedType`1<System.String>>", typeof(NestedType<NestedType<string>>))]
    [TestCase("System.ValueTuple`2<System.String[],System.Int32[,][,,]>", typeof(ValueTuple<string[], int[,,][,]>))]
    [TestCase("System.Int32*", typeof(int*))]
    [TestCase("System.Int32&", null)] // special case
    public void IsSameTypeAs(string managedType, Type typeCheck)
    {
        // special case
        typeCheck ??= typeof(int).MakeByRefType();

        ManagedMethodTokenizer tokenizer = new ManagedMethodTokenizer(managedType, true);

        Assert.That(tokenizer.IsSameTypeAs(typeCheck), Is.True);
    }

    [Test]
    [TestCase("System.Object", typeof(int))]
    [TestCase("System.Version", typeof(IPAddress))]
    [TestCase("GlobalNamespaceType", typeof(OtherGlobalNamespaceType))]
    [TestCase("System.Collections.Generic.Dictionary`2", typeof(Dictionary<string, int>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<,>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<int, string>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.String,System.Int32>", typeof(Dictionary<string, string>))]
    [TestCase("System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.Collections.Generic.List`1<System.String>>>", typeof(List<List<List<int>>>))]
    [TestCase("System.Collections.Generic.Dictionary`2<System.Collections.Generic.Dictionary`2<System.String,System.Int32>,System.Int32>", typeof(Dictionary<Dictionary<string, string>, int>))]
    [TestCase("System.ValueTuple`3<System.String,System.Int32,System.Version>", typeof(ValueTuple<string, int>))]
    [TestCase("System.ValueTuple`3<System.String,System.Int32,System.Version>", typeof(ValueTuple<string, int, string>))]
    [TestCase("uTest_Test.ManagedMethodTokenizerTests+NestedType`1", typeof(NestedType<string>))]
    [TestCase("uTest_Test.ManagedMethodTokenizerTests+NestedType`1<System.String>", typeof(NestedType<>))]
    [TestCase("System.ValueTuple`2<System.String[],System.Int32[,][,,]>", typeof(ValueTuple<string[,], int[][]>))]
    [TestCase("System.Int32*", typeof(string*))]
    [TestCase("System.Int32&", null)] // special case
    public void IsNotSameTypeAs(string managedType, Type typeCheck)
    {
        // special case
        typeCheck ??= typeof(string).MakeByRefType();

        ManagedMethodTokenizer tokenizer = new ManagedMethodTokenizer(managedType, true);

        Assert.That(tokenizer.IsSameTypeAs(typeCheck), Is.False);
    }

    [Test]
    public void IsSameTypeAsWithGenericTypeParameter()
    {
        Type type = typeof(NestedType<>);

        ManagedMethodTokenizer tokenizer = new ManagedMethodTokenizer("Method(!0)", false);

        Assert.That(tokenizer.MoveNext(), Is.True); // Method
        Assert.That(tokenizer.MoveNext(), Is.True); // (
        Assert.That(tokenizer.MoveNext(), Is.True); // !0

        Assert.That(tokenizer.IsSameTypeAs(type.GetGenericArguments()[0]));
    }

    // ReSharper disable once UnusedTypeParameter
    private void TestMethod<T>() { }

    [Test]
    public void IsSameTypeAsWithGenericMethodParameter()
    {
        MethodInfo? method = typeof(ManagedMethodTokenizerTests)
            .GetMethod(nameof(TestMethod), BindingFlags.NonPublic | BindingFlags.Instance);

        Assert.That(method, Is.Not.Null);

        ManagedMethodTokenizer tokenizer = new ManagedMethodTokenizer("Method`1(!!0)", false);

        Assert.That(tokenizer.MoveNext(), Is.True); // Method
        Assert.That(tokenizer.MoveNext(), Is.True); // `1
        Assert.That(tokenizer.MoveNext(), Is.True); // (
        Assert.That(tokenizer.MoveNext(), Is.True); // !!0

        Assert.That(tokenizer.IsSameTypeAs(method!.GetGenericArguments()[0]));
    }

    [Test]
    public void IsSameTypeAsWithGenericNestedTypeParameters()
    {
        Type type = typeof(NestedType<>);
        MethodInfo? method = type.GetMethod("Method", BindingFlags.NonPublic | BindingFlags.Instance);

        Assert.That(method, Is.Not.Null);

        ManagedMethodTokenizer tokenizer = new ManagedMethodTokenizer(
            """
            Method`1(
                System.Collections.Generic.List`1<!!0>,
                System.Collections.Generic.Dictionary`2<!!0,!0>
            )
            """, false);

        Assert.That(tokenizer.MoveNext(), Is.True); // Method
        Assert.That(tokenizer.MoveNext(), Is.True); // `1
        Assert.That(tokenizer.MoveNext(), Is.True); // (

        Type xx0 = method!.GetGenericArguments()[0];
        Type x0 = type.GetGenericArguments()[0];
        Assert.That(tokenizer.IsSameTypeAs(typeof(List<>).MakeGenericType(xx0)));
        Assert.That(tokenizer.IsSameTypeAs(typeof(Dictionary<,>).MakeGenericType(xx0, x0)));
    }

}